### ISSUE TITLE
open a compilation buffer with errors if eval-ts-buffer fails 

### ISSUE THREAD

**Issue by petr-tik** [emacs-ng/emacs-ng#109]
I copy-pasted this JS file, and accidentally hit `eval-ts-buffer` instead of `eval-js-buffer` and ended up seeing these error messages in my Messages buffer.

```bash
funcall-interactively: TS2304 [ERROR]: Cannot find name 'Any'.
var lisp: Any;
          ~~~
    at file:///home/petr_tik/Coding/emacs-ng/$anon$lisp$31610999141.ts:3:11

TS7006 [ERROR]: Parameter 'filename' implicitly has an 'any' type.
export function resolveHomeDir(filename) {
                               ~~~~~~~~
    at file:///home/petr_tik/Coding/emacs-ng/$anon$lisp$31610999141.ts:5:32

TS7006 [ERROR]: Parameter 'filename' implicitly has an 'any' type.
export function openFileAsync(filename) {
                              ~~~~~~~~
    at file:///home/petr_tik/Coding/emacs-ng/$anon$lisp$31610999141.ts:14:31

TS7006 [ERROR]: Parameter 'filename' implicitly has an 'any' type.
    func: filename => openFileAsync(filename)
          ~~~~~~~~
    at file:///home/petr_tik/Coding/emacs-ng/$anon$lisp$31610999141.ts:47:11

Found 4 errors.

```

This made me think that it would be cool to automatically open a eval-ts-compilation buffer and paste the errors there, so people can use already existing goto line and highlighting plugings in compilation/comint modes.

**Comment by petr-tik** [comment]
Thinking about it, the file paths (like `file:///home/petr_tik/Coding/emacs-ng/$anon$lisp$31610999141.ts:47:11`) don't resolve nicely, because eval_js_buffer must be creating an anonymous file.
