### ISSUE TITLE
Panic on `menu-set-font`

### ISSUE THREAD

**Issue by s-kostyaev** [emacs-ng/emacs-ng#125]
My setup is `native-comp` + `webrender`.

After `M-x menu-set-font RET`:
```
RUST_BACKTRACE=1 ./src/emacs
thread '<unnamed>' panicked at 'not implemented', src/wrterm.rs:138:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a62a76047ea24aad7639f14eb3ce0e620b77bdb7/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/a62a76047ea24aad7639f14eb3ce0e620b77bdb7/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/a62a76047ea24aad7639f14eb3ce0e620b77bdb7/library/core/src/panicking.rs:50:5
   3: emacsng::wrterm::x_hide_tip
   4: Fx_hide_tip
   5: x_popup_menu_1
             at ./src/menu.c:1351:5
   6: Ffuncall
             at ./src/eval.c:2977:11
   7: exec_byte_code
             at ./src/bytecode.c:632:12
   8: Ffuncall
             at ./src/eval.c:2993:8
   9: exec_byte_code
             at ./src/bytecode.c:632:12
  10: Ffuncall
             at ./src/eval.c:2993:8
  11: Ffuncall_interactively
             at ./src/callint.c:253:10
  12: Ffuncall
             at ./src/eval.c:2977:11
  13: Fapply
             at ./src/eval.c:2560:12
  14: Fcall_interactively
             at ./src/callint.c:346:14
  15: Ffuncall
             at ./src/eval.c:2977:11
  16: exec_byte_code
             at ./src/bytecode.c:632:12
  17: Ffuncall
             at ./src/eval.c:2993:8
  18: exec_byte_code
             at ./src/bytecode.c:632:12
  19: Ffuncall
             at ./src/eval.c:2993:8
  20: Ffuncall_interactively
             at ./src/callint.c:253:10
  21: Ffuncall
             at ./src/eval.c:2977:11
  22: Fapply
             at ./src/eval.c:2607:24
  23: Fcall_interactively
             at ./src/callint.c:346:14
  24: Ffuncall
             at ./src/eval.c:2977:11
  25: exec_byte_code
             at ./src/bytecode.c:632:12
  26: Ffuncall
             at ./src/eval.c:2993:8
  27: call1
             at ./src/eval.c:2837:10
  28: command_loop_1
             at ./src/keyboard.c:1466:13
  29: internal_condition_case
             at ./src/eval.c:1424:25
  30: command_loop_2
             at ./src/keyboard.c:1094:11
  31: internal_catch
             at ./src/eval.c:1185:25
  32: command_loop
             at ./src/keyboard.c:1073:2
  33: recursive_edit_1
             at ./src/keyboard.c:720:9
  34: Frecursive_edit
             at ./src/keyboard.c:789:3
  35: main
             at ./src/emacs.c:2087:3
  36: __libc_start_main
  37: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Fatal error 6: Aborted
```

**Comment by declanqian** [comment]
After [this commit](https://github.com/emacs-ng/emacs-ng/commit/e959a597fd23ab7530195d123a7bbcd9dc2169c5), I saw `Segmentation fault` for this now

```
$ gdb --args ./src/emacs -Q
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./src/emacs...
(gdb) r
Starting program: /home/declan/Source/emacs/src/emacs -Q
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff3d39640 (LWP 101320)]
[New Thread 0x7ffff3ade640 (LWP 101321)]
[New Thread 0x7ffff1013640 (LWP 101322)]
[New Thread 0x7fffea571640 (LWP 101323)]
[New Thread 0x7fffe9be0640 (LWP 101324)]
[New Thread 0x7fffe924f640 (LWP 101325)]
[New Thread 0x7fffddd54640 (LWP 101326)]
[New Thread 0x7fffe88be640 (LWP 101327)]
[New Thread 0x7fffe86bd640 (LWP 101328)]
[New Thread 0x7fffe84bc640 (LWP 101329)]
[New Thread 0x7fffe82bb640 (LWP 101330)]
[New Thread 0x7fffdd3c3640 (LWP 101331)]
[New Thread 0x7fffdd1c2640 (LWP 101332)]
[New Thread 0x7fffdcfc1640 (LWP 101333)]
[New Thread 0x7fffdcdc0640 (LWP 101334)]
[New Thread 0x7fffdcbbf640 (LWP 101335)]
[New Thread 0x7fffdc9be640 (LWP 101336)]
[New Thread 0x7fffdc7bd640 (LWP 101337)]
[New Thread 0x7fffdc5bc640 (LWP 101338)]
[New Thread 0x7fffdc3bb640 (LWP 101339)]
[New Thread 0x7fff97fff640 (LWP 101340)]
[New Thread 0x7fff97dfe640 (LWP 101341)]

Thread 1 "emacs" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) quit
A debugging session is active.

        Inferior 1 [process 101316] will be killed.

Quit anyway? (y or n) y
```
