### ISSUE TITLE
Current version crashes with doom emacs distribution

### ISSUE THREAD

**Issue by Delanii** [emacs-ng/emacs-ng#253]
**Describe the bug**
Current emacs-ng with native copilation and webrender crashes while running doom emacs distribution. `emacs -q` is running as expected, but with display zoomed up (as in #246 ). This bug occurs on current Manjaro after update to `deno 1.9` (this probably wont be the cause, just something else done in that timeframe); previous build was (probably) OK.

**To Reproduce**
Build emacs from current source:

```shell
./configure --with-native-compilation --with-webrender
```

give priority to emacs-ng in PATH over system emacs:

```
export PATH=~/emacs-ng/src:$PATH
```

rebuild Doom distribution:

```
rm -rf ./.emacs.d/.local/straight
./.emacs.d/bin/doom build
```

**Expected behavior**
Emacs starting up normally, opening file or giving *Doom* splash screen.

**OS**
Linux user-nitroan51554 5.10.34-1-MANJARO #1 SMP Sun May 2 11:29:56 UTC 2021 x86_64 GNU/Linux

**Error callstack**

```
export RUST_BACKTRACE=full
emacs

thread '<unnamed>' panicked at 'not implemented', src/webrender_backend/font.rs:243:5
stack backtrace:
   0:     0x560e4357c983 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560e4357c983 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560e4357c983 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560e4357c983 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560e42cdf54f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/fmt/mod.rs:1094:17
   5:     0x560e4357c2d4 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/io/mod.rs:1580:15
   6:     0x560e4357be55 - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560e4357be55 - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560e4357be55 - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:208:50
   9:     0x560e4357b43f - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:225:9
  10:     0x560e4357b43f - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:591:17
  11:     0x560e43594ba3 - std::panicking::begin_panic_handler::{{closure}}::ha376ab85d95a000e
  12:     0x560e43594b1c - std::sys_common::backtrace::__rust_end_short_backtrace::h6795c8afdd1a77e6
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x560e43594acd - rust_begin_unwind
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
  14:     0x560e429ad9b0 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
  15:     0x560e429ad8fc - core::panicking::panic::h3de4db67bd397eb3
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:50:5
  16:     0x560e42c12584 - emacsng::webrender_backend::font::list_family::h4c5ac91bcb6080ae
  17:     0x560e42b45843 - Ffont_family_list
                               at /home/tomaskrulis/emacs-ng/src/font.c:4340:20
  18:     0x560e42b362da - eval_sub
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2483:15
  19:     0x560e42b36fa6 - apply_lambda
                               at /home/tomaskrulis/emacs-ng/src/eval.c:3152:13
  20:     0x560e42b35eff - eval_sub
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2560:9
  21:     0x560e42b374db - Flet
                               at /home/tomaskrulis/emacs-ng/src/eval.c:1027:18
  22:     0x560e42b3630e - eval_sub
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2436:30
  23:     0x560e42b3659d - Fprogn
                               at /home/tomaskrulis/emacs-ng/src/eval.c:471:13
  24:     0x560e42b3630e - eval_sub
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2436:30
  25:     0x560e42b3630e - eval_sub
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2436:30
  26:     0x560e42b36e1d - Fprogn
                               at /home/tomaskrulis/emacs-ng/src/eval.c:471:13
  27:     0x560e42b36e1d - funcall_lambda
                               at /home/tomaskrulis/emacs-ng/src/eval.c:3285:11
  28:     0x560e42b3383f - Ffuncall
                               at /home/tomaskrulis/emacs-ng/src/eval.c:3024:8
  29:     0x560e42b339b9 - funcall_nil
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2649:3
  30:     0x560e42b32fed - run_hook_with_args
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2826:14
  31:     0x560e42b33164 - Frun_hook_with_args
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2691:10
  32:     0x560e42b33164 - run_hook
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2839:3
  33:     0x560e42b33164 - Frun_hooks
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2673:5
  34:     0x560e42b339a0 - Ffuncall
                               at /home/tomaskrulis/emacs-ng/src/eval.c:3008:11
  35:     0x7f0699df2cc0 - F636f6d6d616e642d6c696e65_command_line_0
  36:     0x560e42b339a0 - Ffuncall
                               at /home/tomaskrulis/emacs-ng/src/eval.c:3008:11
  37:     0x7f0699def8c6 - F6e6f726d616c2d746f702d6c6576656c_normal_top_level_0
  38:     0x560e42b36347 - eval_sub
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2480:15
  39:     0x560e42b37c29 - Feval
                               at /home/tomaskrulis/emacs-ng/src/eval.c:2312:10
  40:     0x560e42b328d7 - internal_condition_case
                               at /home/tomaskrulis/emacs-ng/src/eval.c:1448:25
  41:     0x560e42ab5e56 - top_level_1
                               at /home/tomaskrulis/emacs-ng/src/keyboard.c:1111:5
  42:     0x560e42b35023 - internal_catch
                               at /home/tomaskrulis/emacs-ng/src/eval.c:1198:25
  43:     0x560e42ab50f8 - command_loop
                               at /home/tomaskrulis/emacs-ng/src/keyboard.c:1072:2
  44:     0x560e42aba666 - recursive_edit_1
                               at /home/tomaskrulis/emacs-ng/src/keyboard.c:720:9
  45:     0x560e42aba992 - Frecursive_edit
                               at /home/tomaskrulis/emacs-ng/src/keyboard.c:789:3
  46:     0x560e429f48a3 - main
                               at /home/tomaskrulis/emacs-ng/src/emacs.c:2101:3
  47:     0x7f069db9fb25 - __libc_start_main
  48:     0x560e429f542e - _start
  49:                0x0 - <unknown>
Fatal error 6: Aborted
Backtrace:
emacs(+0x3d2a04)[0x560e42acea04]
emacs(+0x2a8af0)[0x560e429a4af0]
emacs(+0x2a8fb6)[0x560e429a4fb6]
emacs(+0x3d0ccd)[0x560e42accccd]
emacs(+0x3d0db9)[0x560e42accdb9]
/usr/lib/libpthread.so.0(+0x13960)[0x7f069fd63960]
/usr/lib/libc.so.6(gsignal+0x145)[0x7f069dbb4ef5]
/usr/lib/libc.so.6(abort+0x116)[0x7f069db9e862]
emacs(+0xd2cfda)[0x560e43428fda]
emacs(+0xd2cfc9)[0x560e43428fc9]
emacs(+0xe7f619)[0x560e4357b619]
emacs(+0xe7f575)[0x560e4357b575]
emacs(+0xe98ba3)[0x560e43594ba3]
emacs(+0xe98b1c)[0x560e43594b1c]
emacs(+0xe98acd)[0x560e43594acd]
emacs(+0x2b19b0)[0x560e429ad9b0]
emacs(+0x2b18fc)[0x560e429ad8fc]
emacs(+0x516584)[0x560e42c12584]
emacs(+0x449843)[0x560e42b45843]
emacs(+0x43a2da)[0x560e42b362da]
emacs(+0x43afa6)[0x560e42b36fa6]
emacs(+0x439eff)[0x560e42b35eff]
emacs(+0x43b4db)[0x560e42b374db]
emacs(+0x43a30e)[0x560e42b3630e]
emacs(+0x43a59d)[0x560e42b3659d]
emacs(+0x43a30e)[0x560e42b3630e]
emacs(+0x43a30e)[0x560e42b3630e]
emacs(+0x43ae1d)[0x560e42b36e1d]
emacs(+0x43783f)[0x560e42b3383f]
emacs(+0x4379b9)[0x560e42b339b9]
emacs(+0x436fed)[0x560e42b32fed]
emacs(+0x437164)[0x560e42b33164]
emacs(+0x4379a0)[0x560e42b339a0]
/home/tomaskrulis/emacs-ng/src/../native-lisp/28.0.50-4caa5dd5/startup-bbc6ea72-d4083e79.eln(F636f6d6d616e642d6c696e65_command_line_0+0x1620)[0x7f0699df2cc0]
emacs(+0x4379a0)[0x560e42b339a0]
/home/tomaskrulis/emacs-ng/src/../native-lisp/28.0.50-4caa5dd5/startup-bbc6ea72-d4083e79.eln(F6e6f726d616c2d746f702d6c6576656c_normal_top_level_0+0xf06)[0x7f0699def8c6]
emacs(+0x43a347)[0x560e42b36347]
emacs(+0x43bc29)[0x560e42b37c29]
emacs(+0x4368d7)[0x560e42b328d7]
emacs(+0x3b9e56)[0x560e42ab5e56]
emacs(+0x439023)[0x560e42b35023]
...
Aborted (core dumped)
```

**Comment by Delanii** [comment]
Sorry, dupe of #247
