### ISSUE TITLE
webrender: Emacs panicked when open a Wikipedia page using `eww`

### ISSUE THREAD

**Issue by declanqian** [emacs-ng/emacs-ng#330]
**Describe the bug**
webrender Emacs panicked when open a Wikipedia page using `eww`
Tried pages:
https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5
https://en.wikipedia.org/wiki/Main_Page

But it's ok to open https://google.com/

**To Reproduce**
`RUST_BACKTRACE=1 ./src/emacs -Q --eval="(eww \"https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5\")"`

```shell
./configure --with-libgit --with-webrender --with-native-compilation --with-wide-int
```

**Expected behavior**
Don't panick, open the web page like gnu Emacs.
Or at least, display an error message without crashing Emacs

**OS**
Linux thinkpadx1extreme 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux
Also on wayland using Sway with env `MOZ_ENABLE_WAYLAND=1`.

**Error callstack**
```
-*- mode: compilation; default-directory: "~/Workspace/emacs/" -*-
Compilation started at Sat Jun 19 12:59:13

RUST_BACKTRACE=1 ./src/emacs -Q --eval="(eww \"https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5\")"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotFound', crates/webrender/src/font.rs:344:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
   4: webrender::font::open_font
   5: font_open_entity
             at ./src/font.c:2927:21
   6: font_load_for_lface
             at ./src/font.c:3421:12
   7: realize_gui_face
             at ./src/xfaces.c:5960:6
   8: realize_face
             at ./src/xfaces.c:5853:12
   9: lookup_face
             at ./src/xfaces.c:4827:12
  10: face_at_buffer_position
             at ./src/xfaces.c:6517:10
  11: face_at_pos
             at ./src/xdisp.c:4379:14
  12: handle_face_prop
             at ./src/xdisp.c:4475:27
  13: handle_stop
             at ./src/xdisp.c:3854:14
  14: next_element_from_buffer
             at ./src/xdisp.c:8907:4
  15: get_next_display_element
             at ./src/xdisp.c:7496:15
  16: move_it_in_display_line_to
             at ./src/xdisp.c:9264:12
  17: move_it_to
             at ./src/xdisp.c:9923:11
  18: Fwindow_text_pixel_size
             at ./src/xdisp.c:10777:7
  19: F7368722d706978656c2d6275666665722d7769647468_shr_pixel_buffer_width_0
  20: Ffuncall
             at ./src/eval.c:3038:11
  21: F7368722d72656e6465722d74642d31_shr_render_td_1_0
  22: Ffuncall
             at ./src/eval.c:3038:11
  23: F7368722d72656e6465722d7464_shr_render_td_0
  24: Ffuncall
             at ./src/eval.c:3038:11
  25: F7368722d6d616b652d7461626c652d31_shr_make_table_1_0
  26: Ffuncall
             at ./src/eval.c:3038:11
  27: F7368722d6d616b652d7461626c65_shr_make_table_0
  28: Ffuncall
             at ./src/eval.c:3038:11
  29: F7368722d7461672d7461626c652d31_shr_tag_table_1_0
  30: Ffuncall
             at ./src/eval.c:3038:11
  31: F7368722d7461672d7461626c65_shr_tag_table_0
  32: Ffuncall
             at ./src/eval.c:3038:11
  33: F7368722d64657363656e64_shr_descend_0
  34: Ffuncall
             at ./src/eval.c:3038:11
  35: F7368722d7461672d646976_shr_tag_div_0
  36: Ffuncall
             at ./src/eval.c:3038:11
  37: F7368722d64657363656e64_shr_descend_0
  38: Ffuncall
             at ./src/eval.c:3038:11
  39: F7368722d7461672d646976_shr_tag_div_0
  40: Ffuncall
             at ./src/eval.c:3038:11
  41: F7368722d64657363656e64_shr_descend_0
  42: Ffuncall
             at ./src/eval.c:3038:11
  43: F7368722d7461672d646976_shr_tag_div_0
  44: Ffuncall
             at ./src/eval.c:3038:11
  45: F7368722d64657363656e64_shr_descend_0
  46: Ffuncall
             at ./src/eval.c:3038:11
  47: F7368722d7461672d646976_shr_tag_div_0
  48: Ffuncall
             at ./src/eval.c:3038:11
  49: F7368722d64657363656e64_shr_descend_0
  50: Ffuncall
             at ./src/eval.c:3038:11
  51: F7368722d7461672d646976_shr_tag_div_0
  52: Ffuncall
             at ./src/eval.c:3038:11
  53: F7368722d64657363656e64_shr_descend_0
  54: Ffuncall
             at ./src/eval.c:3038:11
  55: F7368722d7461672d646976_shr_tag_div_0
  56: Ffuncall
             at ./src/eval.c:3038:11
  57: F7368722d64657363656e64_shr_descend_0
  58: Ffuncall
             at ./src/eval.c:3038:11
  59: F7368722d7461672d646976_shr_tag_div_0
  60: Ffuncall
             at ./src/eval.c:3038:11
  61: F7368722d64657363656e64_shr_descend_0
  62: Ffuncall
             at ./src/eval.c:3038:11
  63: F7368722d7461672d626f6479_shr_tag_body_0
  64: Ffuncall
             at ./src/eval.c:3038:11
  65: F7368722d64657363656e64_shr_descend_0
  66: Ffuncall
             at ./src/eval.c:3038:11
  67: F7368722d7461672d68746d6c_shr_tag_html_0
  68: Ffuncall
             at ./src/eval.c:3038:11
  69: F7368722d64657363656e64_shr_descend_0
  70: Ffuncall
             at ./src/eval.c:3038:11
  71: F7368722d7461672d62617365_shr_tag_base_0
  72: Ffuncall
             at ./src/eval.c:3038:11
  73: F7368722d64657363656e64_shr_descend_0
  74: Ffuncall
             at ./src/eval.c:3038:11
  75: F7368722d696e736572742d646f63756d656e74_shr_insert_document_0
  76: Ffuncall
             at ./src/eval.c:3038:11
  77: F6577772d646973706c61792d68746d6c_eww_display_html_0
  78: Ffuncall
             at ./src/eval.c:3038:11
  79: F6577772d72656e646572_eww_render_0
  80: Ffuncall
             at ./src/eval.c:3038:11
  81: Fapply
             at ./src/eval.c:2668:24
  82: F75726c2d687474702d61637469766174652d63616c6c6261636b_url_http_activate_callback_0
  83: Ffuncall
             at ./src/eval.c:3038:11
  84: F75726c2d687474702d636f6e74656e742d6c656e6774682d61667465722d6368616e67652d66756e6374696f6e_url_http_content_length_after_change_function_0
  85: Ffuncall
             at ./src/eval.c:3038:11
  86: F75726c2d687474702d67656e657269632d66696c746572_url_http_generic_filter_0
  87: Ffuncall
             at ./src/eval.c:3038:11
  88: Fapply
             at ./src/eval.c:2668:24
  89: apply1
             at ./src/eval.c:2884:43
  90: internal_condition_case_1
             at ./src/eval.c:1502:25
  91: read_and_dispose_of_process_output
             at ./src/process.c:6171:5
  92: read_process_output
             at ./src/process.c:6081:3
  93: wait_reading_process_output
             at ./src/process.c:5766:16
  94: kbd_buffer_get_event
             at ./src/keyboard.c:3885:4
  95: read_event_from_main_queue
             at ./src/keyboard.c:2159:7
  96: read_decoded_event_from_main_queue
             at ./src/keyboard.c:2223:11
  97: read_char
             at ./src/keyboard.c:2853:11
  98: read_key_sequence
             at ./src/keyboard.c:9543:12
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Fatal error 6: Aborted
Backtrace:
./src/emacs(+0x42dcc1)[0x55806336fcc1]
./src/emacs(+0x2fea93)[0x558063240a93]
./src/emacs(+0x2fef5d)[0x558063240f5d]
./src/emacs(+0x42bfed)[0x55806336dfed]
./src/emacs(+0x42c0d9)[0x55806336e0d9]
/usr/lib/libpthread.so.0(+0x13870)[0x7fe91ded2870]
/usr/lib/libc.so.6(gsignal+0x142)[0x7fe91bbb9d22]
/usr/lib/libc.so.6(abort+0x116)[0x7fe91bba3862]
./src/emacs(+0xdae84a)[0x558063cf084a]
./src/emacs(+0xdae839)[0x558063cf0839]
./src/emacs(+0xefec19)[0x558063e40c19]
./src/emacs(+0xefeb75)[0x558063e40b75]
./src/emacs(+0xf181a3)[0x558063e5a1a3]
./src/emacs(+0xf1811c)[0x558063e5a11c]
./src/emacs(+0xf180cd)[0x558063e5a0cd]
./src/emacs(+0x306190)[0x558063248190]
./src/emacs(+0x306852)[0x558063248852]
./src/emacs(+0x11442ab)[0x5580640862ab]
./src/emacs(+0x11432c3)[0x5580640852c3]
./src/emacs(+0x4ac48c)[0x5580633ee48c]
./src/emacs(+0x4acb7a)[0x5580633eeb7a]
./src/emacs(+0x402808)[0x558063344808]
./src/emacs(+0x4041f0)[0x5580633461f0]
./src/emacs(+0x406221)[0x558063348221]
./src/emacs(+0x36d212)[0x5580632af212]
./src/emacs(+0x3850ce)[0x5580632c70ce]
./src/emacs(+0x37f755)[0x5580632c1755]
./src/emacs(+0x3872f8)[0x5580632c92f8]
./src/emacs(+0x3852b5)[0x5580632c72b5]
./src/emacs(+0x382818)[0x5580632c4818]
./src/emacs(+0x38769a)[0x5580632c969a]
./src/emacs(+0x39215a)[0x5580632d415a]
/home/declan/.config/emacs/eln-cache/28.0.50-ba0d5222/shr-375ad325-91ad30b0.eln(F7368722d706978656c2d6275666665722d7769647468_shr_pixel_buffer_width_0+0x71)[0x7fe8a5c553f1]
./src/emacs(+0x4923b0)[0x5580633d43b0]
/home/declan/.config/emacs/eln-cache/28.0.50-ba0d5222/shr-375ad325-91ad30b0.eln(F7368722d72656e6465722d74642d31_shr_render_td_1_0+0x7c9)[0x7fe8a5c56089]
./src/emacs(+0x4923b0)[0x5580633d43b0]
/home/declan/.config/emacs/eln-cache/28.0.50-ba0d5222/shr-375ad325-91ad30b0.eln(F7368722d72656e6465722d7464_shr_render_td_0+0x2bb)[0x7fe8a5c557eb]
./src/emacs(+0x4923b0)[0x5580633d43b0]
/home/declan/.config/emacs/eln-cache/28.0.50-ba0d5222/shr-375ad325-91ad30b0.eln(F7368722d6d616b652d7461626c652d31_shr_make_table_1_0+0x53a)[0x7fe8a5c54d0a]
./src/emacs(+0x4923b0)[0x5580633d43b0]
/home/declan/.config/emacs/eln-cache/28.0.50-ba0d5222/shr-375ad325-91ad30b0.eln(F7368722d6d616b652d7461626c65_shr_make_table_0+0xeb)[0x7fe8a5c5471b]
...

Compilation aborted (core dumped) at Sat Jun 19 12:59:20
```

**Comment by declanqian** [comment]
Fixed on https://github.com/emacs-ng/emacs-ng/pull/350
