### ISSUE TITLE
WR/Winit emacsclient does not work properly

### ISSUE THREAD

**Issue by declantsien** [emacs-ng/emacs-ng#402]
**Describe the bug**
WR Emacs got segmentation fault when switching between frames in [fg]daemon mode.

**To Reproduce**

```shell
./configure --with-webrender
```

 - `./src/emacs --fg-daemon -Q`
 - `./lib-src/emacsclient -c -n`
 - `./lib-src/emacsclient -c -n`
 - Use mouse to switch between frames

**Expected behavior**

**OS**
```
uname -a
Linux thinkpadx1extreme 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux
```

**Error callstack**
gdb bt output
```
Thread 1 "emacs" received signal SIGSEGV, Segmentation fault.
0x0000555555b0ea5e in wrterm::term::mouse_position ()
(gdb) bt
#0  0x0000555555b0ea5e in wrterm::term::mouse_position ()
#1  0x00005555556ba449 in kbd_buffer_get_event (used_mouse_menu=0x7fffffffdd6b,
    end_time=0x0, kbp=<synthetic pointer>) at keyboard.c:4086
#2  read_event_from_main_queue (used_mouse_menu=0x7fffffffdd6b,
    local_getcjmp=0x7fffffffd980, end_time=0x0) at keyboard.c:2182
#3  read_decoded_event_from_main_queue (used_mouse_menu=<optimized out>,
    prev_event=<optimized out>, local_getcjmp=<optimized out>,
    end_time=<optimized out>) at keyboard.c:2246
#4  read_char (commandflag=1, map=0x555558a40eb3, prev_event=0x0,
    used_mouse_menu=0x7fffffffdd6b, end_time=0x0) at keyboard.c:2876
#5  0x00005555556bbf00 in read_key_sequence (keybuf=<optimized out>, prompt=0x0,
    dont_downcase_last=<optimized out>, can_return_switch_frame=true,
    fix_current_buffer=true, prevent_redisplay=<optimized out>) at keyboard.c:9569
#6  0x00005555556bd88c in command_loop_1 () at keyboard.c:1376
#7  0x000055555572b2d7 in internal_condition_case (
    bfun=bfun@entry=0x5555556bd6a0 <command_loop_1>, handlers=handlers@entry=0x90,
    hfun=hfun@entry=0x5555556b4460 <cmd_error>) at eval.c:1478
#8  0x00005555556ae886 in command_loop_2 (handlers=handlers@entry=0x90)
    at keyboard.c:1117
#9  0x000055555572da03 in internal_catch (tag=tag@entry=0xe070,
    func=func@entry=0x5555556ae860 <command_loop_2>, arg=arg@entry=0x90) at eval.c:1198
#10 0x00005555556ae821 in command_loop () at keyboard.c:1095
#11 0x00005555556b405c in recursive_edit_1 () at keyboard.c:720
#12 0x00005555556b43a5 in Frecursive_edit () at keyboard.c:792
#13 0x00005555555ee827 in main (argc=<optimized out>, argv=<optimized out>)
    at emacs.c:2315
```

**Comment by declantsien** [comment]
Emacs does not crash when built with WR/Winit anymore. But emacsclient -cn does nothing.
It quit silently.
